theme = "base16_default_dark"

[editor]
bufferline = "multiple"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'<' = '>'

[editor.soft-wrap]
enable = true

#[keys.normal]
#C-t = [":open Daily.md", ":write!", ":sh daily_note", ":reload", ":goto 5"]
