for file in ~/.{bash_sensible,path,bash_prompt,exports,bash_aliases,functions,extra}; do
       [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


export GOPATH=$HOME/work/go
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$GOPATH/bin:$PATH:/usr/bin:/usr/sbin:/bin:/usr/local/opt/go/libexec/bin";
export LSCOLORS=exfxcxdxbxegedabagacad
export CLICOLOR=1

. ~/bin/z.sh
