-- disable netrw as per https://github.com/kyazdani42/nvim-tree.lua
vim.g.loaded = 1
vim.g.loaded_netrwPlugin = 1
require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.mason")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
-- require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
-- require("user.trouble")
require("user.go")
