[tasks.common]
  links = [["bin"],
            [".bashrc", "dotfiles/bashrc"],
            [".bash_profile", "dotfiles/bash_profile"],
            [".bash_prompt", "dotfiles/bash_prompt"],
  ]

[tasks.default]
  deps = ["common"]
