add_newline = true

[status]
style = "bg:blue"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[nodejs]
format = "via [🤖 $version](bold green) "

[time]
disabled = false

[python]
python_binary = "python3"

[red]
disabled = true

[zig]
disabled = true

[vcsh]
disabled = true

[vagrant]
disabled = true

[swift]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[singularity]
disabled = true


[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[lua]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[purescript]
disabled = true


