[tasks.common]
  links = [["bin"],
            [".bashrc", "bash/bashrc"],
            [".bash_profile", "bash/bash_profile"],
            [".bash_aliases", "bash/bash_aliases"],
            [".bash_prompt", "bash/bash_prompt"],
            [".inputrc", "bash/inputrc"],
            [".bash_sensible", "bash/sensible.bash"],
            [".bash_ssh", "bash/bash_ssh"],
            [".ssh/rc", "bash/sshrc"],
            [".tmux.conf", "tmux/tmux.conf"],
            [".tmux.master", "tmux/tmux.master"],
            [".tmux.shared", "tmux/tmux.shared"],
            [".tmux.uber", "tmux/tmux.uber"],
  ]

[tasks.default]
  deps = ["common", "nvim"]

[tasks.nvim]
  accepts = [["which", "nvim"]]
  cmds = [["nvim", "+PlugInstall", "+qall"]]
  links = [[".local/share/", "nvim/share"],
	   [".config/nvim", "nvim/config"]]
  
