# tell omz where it lives
ANTIBODY_HOME="$(antibody home)"
export ZSH="$ANTIBODY_HOME"/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh
source $ZSH/oh-my-zsh.sh

source <(antibody init)
antibody bundle < ~/.zsh_plugins


#ZSH_THEME=


# quit bugging me!
DISABLE_AUTO_UPDATE="false"

#autoload -Uz compinit promptinit
autoload -Uz compinit
#promptinit
compinit
#prompt agnoster
#prompt pure

#######################
# environment settings
#######################

export PATH="$PATH:$HOME/work/go/bin:$HOME/go/bin"
export EDITOR="nvim"
export TERM="xterm-256color"
ulimit -n 4096

alias vim="nvim"
alias vi="nvim"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias up="cd .."

bindkey -e
unsetopt beep                   # no bell on error
unsetopt list_beep              # no bell on ambiguous completion
IGNOREEOF=10
set -o ignoreeof # disable exit with ctrl-d

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
