source /opt/homebrew/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-completions
antigen bundle mafredri/zsh-async
antigen bundle belak/zsh-utils path:/editor
antigen bundle belak/zsh-utils path:/history

antigen bundle macos
antigen bundle git
antigen bundle aws
antigen bundle docker
antigen bundle brew
antigen bundle pip
antigen bundle command-not-found

antigen apply



#ZSH_THEME=


# quit bugging me!
DISABLE_AUTO_UPDATE="false"

#autoload -Uz compinit promptinit
autoload -Uz compinit
#promptinit
compinit
#prompt agnoster
#prompt pure

#######################
# environment settings
#######################

export PATH="$PATH:$HOME/work/go/bin:$HOME/go/bin"
export EDITOR="nvim"
export TERM="xterm-256color"
ulimit -n 4096

alias vim="nvim"
alias vi="nvim"
alias code="/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code"
alias up="cd .."

bindkey -e
unsetopt beep                   # no bell on error
unsetopt list_beep              # no bell on ambiguous completion
IGNOREEOF=10
set -o ignoreeof # disable exit with ctrl-d

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
