#!/bin/bash

# Set up ssh-agent
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initializing new SSH agent..."
    touch $SSH_ENV
    chmod 600 "${SSH_ENV}"
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' >> "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    ## only start an agent if we didn't get one forwarded from the outside
    if [[ ! -v SSH_AUTH_SOCK ]] ; then
        kill -0 $SSH_AGENT_PID 2>/dev/null || {
            start_agent
        }
    fi
else
    start_agent
fi
